'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useAuth } from '@/components/AuthProvider'

type ManagedUser = { id: number; username: string; display_name: string; role: 'admin' | 'operator' | 'reader'; is_active: boolean; created_at: string; last_login_at: string | null }
const roleLabel = { admin: '管理员', operator: '业务人员', reader: '只读人员' }

export default function UserManagementPage() {
  const { user } = useAuth(); const [users, setUsers] = useState<ManagedUser[]>([]); const [message, setMessage] = useState(''); const [form, setForm] = useState({ username: '', display_name: '', password: '', role: 'operator' })
  const load = async () => { const r = await fetch('/api/admin/users'); if (r.ok) setUsers(await r.json()); else setMessage('无管理员权限或加载失败') }
  useEffect(() => { if (user?.role === 'admin') void load() }, [user])
  async function create(e: FormEvent) { e.preventDefault(); const r = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!r.ok) return setMessage((await r.json()).detail || '创建失败'); setForm({ username: '', display_name: '', password: '', role: 'operator' }); setMessage('账号已创建'); void load() }
  async function patch(id: number, body: object) { const r = await fetch(`/api/admin/users/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); setMessage(r.ok ? '账号已更新' : (await r.json()).detail || '更新失败'); void load() }
  async function reset(id: number) { const password = window.prompt('输入新密码（至少 8 位）'); if (!password) return; const r = await fetch(`/api/admin/users/${id}/reset-password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); setMessage(r.ok ? '密码已重置，该用户现有会话已失效' : (await r.json()).detail || '重置失败') }
  if (user?.role !== 'admin') return <p className="text-sm text-slate-500">需要管理员权限。</p>
  return <section className="space-y-7"><div><p className="text-xs font-semibold tracking-[.18em] text-blue-700">ADMINISTRATION</p><h1 className="mt-2 text-2xl font-bold text-slate-900">账号与权限管理</h1><p className="mt-1 text-sm text-slate-500">工程和组价数据默认归创建者所有；管理员可访问全部数据。</p></div>{message && <div className="rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}<form onSubmit={create} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-4"><input required placeholder="登录账号" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} className="rounded border px-3 py-2" /><input required placeholder="姓名" value={form.display_name} onChange={e => setForm({ ...form, display_name: e.target.value })} className="rounded border px-3 py-2" /><input required minLength={8} type="password" placeholder="初始密码" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="rounded border px-3 py-2" /><div className="flex gap-2"><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} className="min-w-0 flex-1 rounded border px-2 py-2"><option value="operator">业务人员</option><option value="reader">只读人员</option><option value="admin">管理员</option></select><button className="rounded bg-blue-900 px-4 text-sm font-medium text-white">新建</button></div></form><div className="overflow-hidden rounded-xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">账号</th><th className="px-5 py-3">角色</th><th className="px-5 py-3">状态</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody>{users.map(item => <tr key={item.id} className="border-t"><td className="px-5 py-3"><p className="font-medium">{item.display_name}</p><p className="text-xs text-slate-500">{item.username}</p></td><td className="px-5 py-3"><select value={item.role} onChange={e => void patch(item.id, { role: e.target.value })} className="rounded border bg-white px-2 py-1">{Object.entries(roleLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></td><td className="px-5 py-3"><button onClick={() => void patch(item.id, { is_active: !item.is_active })} className={`rounded-full px-2.5 py-1 text-xs font-medium ${item.is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{item.is_active ? '启用' : '已停用'}</button></td><td className="px-5 py-3 text-right"><button onClick={() => void reset(item.id)} className="text-blue-700 hover:underline">重置密码</button></td></tr>)}</tbody></table></div><OwnershipTransfer onDone={setMessage} /></section>
}

function OwnershipTransfer({ onDone }: { onDone: (message: string) => void }) {
  const [type, setType] = useState('boq-project'); const [id, setId] = useState(''); const [owner, setOwner] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); const r = await fetch(`/api/admin/ownership/${type}/${id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ owner_user_id: Number(owner) }) }); onDone(r.ok ? '资产所有者已转交' : (await r.json()).detail || '转交失败') }
  return <form onSubmit={submit} className="flex flex-wrap items-end gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5"><div className="text-sm"><p className="font-semibold">资产所有者转交</p><p className="text-slate-500">将历史或离职用户的工程、任务转交给另一账号。</p></div><select value={type} onChange={e => setType(e.target.value)} className="rounded border px-2 py-2"><option value="boq-project">工程</option><option value="manual-project">人工工程</option><option value="pricing-task">单条组价任务</option><option value="pricing-batch">批量组价任务</option></select><input required type="number" min="1" placeholder="资产 ID" value={id} onChange={e => setId(e.target.value)} className="w-28 rounded border px-2 py-2" /><input required type="number" min="1" placeholder="新所有者 ID" value={owner} onChange={e => setOwner(e.target.value)} className="w-32 rounded border px-2 py-2" /><button className="rounded bg-slate-800 px-4 py-2 text-sm text-white">转交</button></form>
}
